@baseUrl = http://localhost:3000
@JwtToken = {{authLogin.response.body.accessToken}}

### Do login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "kaique1@email.com",
  "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{JwtToken}}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Kaique Lurdes",
  "email": "kaique@email.com",
  "password": "123456"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "name": "Caique Lucidez",
  "email": "kaique1@email.com"
}
