@baseUrl = http://localhost:3000

### Do login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "laionlurdes@hotmail.com",
  "password": "123"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Postal Lurdes",
  "email": "postal@email.com",
  "password": "sissy"
}
